### ISSUE TITLE
crashing DrRacket

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/accelerack#44]
This works fine if put in a buffer and run:

```Racket
(require accelerack)
(define x (acc-array (1 2 3)))
(acc-array->list x)```
```

It also works fine if I type `racket` on the command line and type it there at the REPL.  But if I run the last line on the DrRacket REPL on the other hand (or even just "`x`"), DrRacket crashes immediately.

Maybe @samth has an idea about the difference in running environment here.

**Comment by samth** [comment]
What does crashes mean? Segfaults, errors, doesn't print anything?

**Comment by rrnewton** [comment]
On linux it exited immediately.  I'll run again tomorrow to see if anything was on stderr on the terminal.  I suppose it's runnable under GDB?

On Mac w/, actually right now it's just killing the "evaluation thread" and bringing up a message to that effect.  The GUI stays up.

**Comment by prak5190** [comment]
I am trying with : `(map (lambda(x) (acc-array 1)) (range 1000))` 
With background expansion enabled - It definitely crashes within 3-4 tries with memory usage of a gb
and gives : 
SIGSEGV MAPERR si_code 1 fault on addr 0x36
Aborted (core dumped)

Without background expansion, it definitely seems to go much longer (though it still crashes at times), but it does crash at times with similar message.
It takes a few more attempts to crash when `acc-array->sexp` (which is the new `acc-array->list`) is used in the map. Like this `   (map (lambda(x) (acc-array->sexp (acc-array 1))) (range 1000))`

It might be related to the ffi since even with with the racket command line if I run something like 
`(map (lambda(x) (map (lambda(x) (acc-array 1)) (range 1000))) (range 1000))` 
It does crash with 
SIGSEGV MAPERR si_code 1 fault on addr 0x102
or 
```
 ptr-ref*: contract violation
	  expected: ctype?
	  given: 'empty_type```
```

I am on racket 6.3 , DrRacket 6.3 on Ubuntu 15.04 , i7 - 8gb

**Comment by samth** [comment]
That makes it sound like the crash varies based on allocation and GC, so it's not surprising that it would be different in DrRacket.
