### ISSUE TITLE
Shapes are allowed empty dimensions

### ISSUE THREAD

**Issue by projanen** [iu-parfunc/accelerack#6]
Shapes are allowed to have empty dimensions, such as (Z 2 0 2).

Need to disallow this for shapes but allow it for indices.  Need to rethink the sub-typing there.

**Comment by eholk** [comment]
Does it harm anything to let them be there? They wouldn’t be able to contain any data, but they are useful for bookkeeping sometimes. For example in the fissioning rules, it’s nice not to have to worry about splitting a size one array.

**Comment by projanen** [comment]
I was wondering if there were any uses for them.  What about this?

Array (Z :. 3 :. -3 :. 5) []
Array (Z :. 2 :. -2 :. -2) [1,2,3,4,5,6,7,8]

**Comment by tmcdonell** [comment]
What is your argument for not allowing empty shapes?

**Comment by projanen** [comment]
Eric, do you not worry about splitting size zero arrays?  Don't you need a base case at some point?

**Comment by projanen** [comment]
What got me thinking about shapes with zero was that I had an off-by-one error in my indexing of arrays--I allowed for indices like (Z 2 0 3) for arrays of shape (Z 3 3 3).  So I thought it would be nice to think of arrays as having shapes that are exactly shifted in their numbers by one from what the valid indices are.  And I didn't see a need for empty shapes.

Additionally, one of Accelerack's initial audiences will be students.  And one of our teaching methodologies includes limiting them to what they need as one way of supporting the effort to generate nice error messages.  For instance, before they are taught about mutation, there are no parameter-less functions.  Until they are taught first-class functions, function identifiers may only used in the first position of an s-expr.

I see now the only way to have an empty shape/array is to have one of its dimensions be zero.  I'm still not sure that any shape beyond (Z 0) is necessary for this.  But I see now how they can come from computations, and they are not necessarily ill-formed.  I supposed a rectangular prism could have a side-length of zero.  It wouldn't be solid, it wouldn't have any volume, but it could be considered a multi-dimensional object in some regards.  If such things are done in practice, then there's an argument for them.  I'm mainly looking to keep things simpler.  But Accelerack should be general; we want to follow Accelerate's lead.  Simplification for teaching purposes can be a special version of Accelerack.

I made a mention of zeroes in the new issue about negatives, AccelerateHS/accelerate#248.

**Comment by eholk** [comment]
@projanen - In the semantics I had everything bottom out at size 1 arrays, since you obviously won't gain anything by splitting these. Still, I think the math is simpler when you don't have a lot of side conditions about sizes being greater than zero. The rewrite rules still work if you're allowed to split 0-sized arrays, but they won't terminate because you'd end up with two 0-sized arrays, which can be split into four, and so on.

**Comment by rrnewton** [comment]
Yes, fissioning needs to bottom out.

But I think zero-length in arbitrary dimensions is important because you may in general do data-dependent things like a Filter.  It's hard to think of a good multi-dimensional example, but in the 1D case filter can easily result in (Z 0).

**Comment by arcfide** [comment]
On a side note, languages like APL and J definitely use zero-length dimensions for their shapes, and they are pretty important. While you might not encounter them every-day, I certainly deal with them every program that I write, on multiple occasions. I don't know how different Accelerate is (a lot, I'd imagine), so that could change things, but I'd be surprised if zero-length dimensions weren't important..
